### ISSUE TITLE
Latest VMware tools (10.1.2) default flag aborts installation

### ISSUE THREAD

**Issue by sl4m** [rasa/vmware-tools-patches#125]
It looks like when using the `--default` flag it aborts the installation in the latest VMware tools (10.1.2). I had to manually run `vmware-install.pl` to install it and not use `compile.sh`.

```
vagrant@vm:/tmp/vmware-tools-patches/vmware-tools-patches/vmware-tools-distrib$ sudo ./vmware-install.pl
open-vm-tools packages are available from the OS vendor and VMware recommends
using open-vm-tools packages. See http://kb.vmware.com/kb/2073803 for more
information.
Do you still want to proceed with this installation? [no] yes
```

**Comment by maaaaz** [comment]
I experienced the same kind of problem: the `--clober-kernel-modules` option does not seem to exist in `vmware-install.pl` script version `VMWare Tools 10.2.5 build-8068393 for Linux installer`

Running `./vmware-install.pl --default --force-install` manually instead of `./compile.sh` fixed my issue.

Cheers.

**Comment by ssolidus** [comment]
@rasa you can close this, I fixed it a few versions ago. There is now a seperate script for the older versions
